name: CI/CD – Build & Deploy Infrastructure

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "terraform/**"
      - "Bootstrap/**"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cloudcart-app
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-west-2' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout Repo ---
      - name: Checkout
        uses: actions/checkout@v4

      # --- Build Docker Image ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      # --- Set up Terraform ---
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # --- Configure AWS ---
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # --- Terraform Commands ---
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
